# Generated by Django 3.1.7 on 2022-01-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='json_path',
            field=models.FilePathField(default='', path='static/places/', verbose_name='Адрес json файла'),
        ),
    ]
