# Generated by Django 3.1.7 on 2022-01-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_json_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='json_path',
        ),
    ]
