# Generated by Django 3.2.11 on 2022-01-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lng', 'lat')},
        ),
    ]
