# Generated by Django 3.2.11 on 2022-02-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20220204_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'image')},
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
